### ISSUE TITLE
Problem with accented characters

### ISSUE THREAD

**Issue by LemonBoy** [chaoren/vim-wordmotion#1]
The first line is a sample line, I expect to reach the `g` with `3w` (see the first line) but I actually have to use `5w` since the accented character isn't taken into account as alphanumeric character.

```
abc déf ghi
^   ^   ^
^   ^^^ ^
```

**Comment by chaoren** [comment]
Should be fixed with 5cc6c83916f51cdae0552deb330a5799b3ddeb16. Please verify.

**Comment by LemonBoy** [comment]
It seems to work fine, thanks :)
