### ISSUE TITLE
Feature request: Toggling

### ISSUE THREAD

**Issue by vbauerster** [chaoren/vim-wordmotion#11]
I'd like to see toggling option in this plugin. For example, let user define a normal mapping to toggle on and off. It is more robust than having `g:wordmotion_prefix`,  and adheres to vim's modal philosophy. Like, when I press predefined toggle map, I'm in wordmotion mode, press again, I exit wordmotion mode.

**Comment by chaoren** [comment]
I don't want this feature in the plugin, but you can do this yourself with the following code snippet in your .vimrc.

```
let g:wordmotion_prefix = '<Plug>(wordmotion)'
let g:wordmotion_mappings = {
            \ 'aw' : '<Plug>(wordmotion)aw',
            \ 'iw' : '<Plug>(wordmotion)iw'
            \ }
let s:wordmotion_on = 0
function! ToggleWordmotion()
    let s:wordmotion_on = !s:wordmotion_on
    for l:motion in [ 'w', 'e', 'b', 'ge', 'aw', 'iw' ]
        for l:mode in [ 'n', 'x', 'o' ]
            if l:mode == 'n' && l:motion =~ '.w'
                continue
            endif
            if s:wordmotion_on
                let l:rhs = '<Plug>(wordmotion)' . l:motion
                execute l:mode . 'map' l:motion l:rhs
            else
                execute l:mode . 'unmap' l:motion
            endif
        endfor
    endfor
endfunction
```

You can then map something to `call ToggleWordmotion()` to toggle it.
