### ISSUE TITLE
Handle c_<C-R>_<C-W>

### ISSUE THREAD

**Issue by SevereOverfl0w** [chaoren/vim-wordmotion#12]
Pretty much title, it would be nice to use wordmotions in the command line insertion.

**Comment by chaoren** [comment]
Done. Please let me know if you run into any problems with it.

**Comment by SevereOverfl0w** [comment]
I forgot to mention also <C-R>_<C-A> which is for WORD.

I will test when I'm online soon. Thank you for this.

On 16 Jun 2017 5:40 am, "Chaoren Lin" <notifications@github.com> wrote:

Done. Please let me know if you run into any problems with it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chaoren/vim-wordmotion/issues/12#issuecomment-308931422>,
or mute the thread

**Comment by chaoren** [comment]
I'm aware of `<C-R><C-A>`, but the plugin doesn't deal with `WORD`s (e.g., we leave `W`, `E`, `B` alone).
