### ISSUE TITLE
Add `ge` motion

### ISSUE THREAD

**Issue by fictionic** [chaoren/vim-wordmotion#14]
The four word (not WORD) motions are `w`, `e`, `b`, and `ge`. This plugin only works for the first three. It'd be great to have all four. Seems really simple to add. Thanks for the awesome plugin!

**Comment by chaoren** [comment]
`ge` does work. Are you having issues with a specific combination of settings?

**Comment by fictionic** [comment]
Huh, you're right. Don't know what was happening that caused me to think it wasn't. It was definitely not an isolated incident. But I retract everything haha. Thanks for the quick response!
