### ISSUE TITLE
Insert mode navigation

### ISSUE THREAD

**Issue by hannasm** [chaoren/vim-wordmotion#16]
Trying to use `<S-Left>` and `<S-Right>`, `<C-Left>` and `<C-Right>` to navigate word boundaries while in insert mode and i'm back in the dark ages again!

I can't seem to find any easy example of how to map a keybinding to call the wordmotion navigation either.

**Comment by chaoren** [comment]
Use `g:wordmotion_prefix` or `g:wordmotion_mappings` to create normal mode mappings, then use `<C-\><C-O>` to create insert mode mappings to the normal mode mappings. E.g.,
```
let g:wordmotion_prefix = '<Plug>(wordmotion)'
imap <S-Right> <C-\><C-O><Plug>(wordmotion)w
imap <S-Left> <C-\><C-O><Plug>(wordmotion)b
```

Relevant documentation:
```
:help g:wordmotion_prefix
Use g:wordmotion_prefix to apply a common prefix to each of the default word motion mappings.

:help g:wordmotion_mappings
Use g:wordmotion_mappings to individually replace the default word motion mappings.

:help i_CTRL-\_CTRL-O
CTRL-O		execute one command, return to Insert mode   *i_CTRL-O*

CTRL-\ CTRL-O	like CTRL-O but don't move the cursor	     *i_CTRL-\_CTRL-O*
```
