### ISSUE TITLE
dW needs to match the behavior of dw

### ISSUE THREAD

**Issue by kutsan** [chaoren/vim-wordmotion#19]
The behaviour that you mentioned in caveats section often becomes inconsistent because default `dW` still behaves like `dE`. So, it would be awesome if you can rebind `W` to work like `w`.

**Comment by chaoren** [comment]
I don't want to touch `W` unless absolutely necessary, so if this were to be implemented I would have to hide it behind a flag.

How important is this to you? Is it just a neatness and consistency thing that you noticed or do you actually do `dW` frequently and wish it behaved like this plugin's `dw`?

I've actually had people complain that I changed the `dw` behavior from vanilla vim, but it just happened to be easier to write. Similarly, leaving `W` alone is much easier to maintain.

**Comment by chaoren** [comment]
You can get the behavior you want with:
```
onoremap W :<C-U>normal! vWh<CR>
```
I'll add this to the docs.
