### ISSUE TITLE
Allow the user to set custom mappings

### ISSUE THREAD

**Issue by LemonBoy** [chaoren/vim-wordmotion#2]
For example I'd like to have `vim-wordmotion` motion mapped to `W`, `B`, `E`, `gE`, `aW`, `iW` but I currently don't have any clean way to do so beside using a bogus custom prefix and then remapping the keys by hand.
I'd suggest to provide a way for the user to provide some custom mappings, maybe via a list/dictionary

**Comment by chaoren** [comment]
Done. 81eb06c5ef8e9adf6e12c30fdadab964b69e1eb3.
