### ISSUE TITLE
Dot repeat of `ciw` emits 'AOrInnerWordMotion' output if 'set noshowmode' is set.

### ISSUE THREAD

**Issue by bluz71** [chaoren/vim-wordmotion#20]
Hello,

In the command line area I am seeing spurious output from this wordmotion plugin when `set noshowmode` is set.

Steps to produce the issue:

- `set noshowmode`

- Edit a file such as the following with the cursor positioned on the 1st line inside **Bar**:

```
FooBarFoo
BarFooBar
```

- Do `ciw` to anything (e.g **Car**)

- Move cursor to 2nd line inside Foo and hit dot `.` to repeat the change

- Look in the command line area, spurious output will be emitted, in my case `:call <SNR>10_AOrInnerWordMotion(v:count1, 'o', 1)`. Note, the actual change word operation is being performed correctly.

When `showmode` is set (aka the Vim default) there is no spurious output.

Maybe a `<silent>` directive is needed somewhere?

Thanks for a great plugin.

**Comment by chaoren** [comment]
Hi, thanks for using the plugin.

Vim's dot operator has a couple of known issues when interacting with custom commands.
This appears to be one of them.

E.g.,
https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L1494
```
Using "." to repeat an Ex command puts that command in history.  Probably
should not happen.  If the command is the result of a mapping it's not put in
history either. (Jacob Niehus, 2014 Nov 2)
Patch from Jacob, Nov 2.
```

All of the mappings used have `<silent>` on them. If they were missing, you would see the output from the regular `ciw`.

I'm actually surprised that the extra output is the only thing broken with dot right now. I think I remember `[count]` on the dot operator not working when I first wrote this plugin.

If you want to file a bug against vim, you can reproduce this with
```
onoremap <silent>\w :normal w<CR>
```
Then `d\w` and repeat it with `.`.

**Comment by bluz71** [comment]
Ok.

Thanks for taking the time with such a comprehensive answer.

Plugin is working with dot, so maybe I should count myself fortunate.

Best regards.

**Comment by daedroza** [comment]
Is there a way I can restore the original behavior of ciw?

**Comment by chaoren** [comment]
I'm not sure what you're talking about. Please create a new issue with examples (what the plugin currently does, what do you expect the plugin to do, etc).

**Comment by tuurep** [comment]
I think this issue should remain open, it's a big problem: all dot-repeats are noisy.

I've found success fixing this on Neovim using the `<cmd>` key instead of a mapping using `:`

```diff
diff --git a/plugin/wordmotion.vim b/plugin/wordmotion.vim
index 8aa633d..f854b4d 100644
--- a/plugin/wordmotion.vim
+++ b/plugin/wordmotion.vim
@@ -52,7 +52,7 @@ for s:_.motion in s:_.motions
 		let s:_.f = printf("'%s'", s:_.flags[tolower(s:_.motion)])
 		let s:_.u = s:_.motion =~# '\u'
 		let s:_.args = join(['v:count1', s:_.m, s:_.f, s:_.u, '[]'], ', ')
-		let s:_.rhs = printf(':<C-U>call wordmotion#motion(%s)<CR>', s:_.args)
+		let s:_.rhs = printf('<cmd>call wordmotion#motion(%s)<CR>', s:_.args)
 		execute s:_.mode . 'noremap' '<silent>' s:_.map s:_.rhs
 		call s:_.add_existing(s:_.mode, s:_.map, s:_.rhs)
 		if s:_.nomap
@@ -80,7 +80,7 @@ for s:_.motion in s:_.motions
 		let s:_.i = s:_.inner[tolower(s:_.motion)]
 		let s:_.u = s:_.motion =~# '\u'
 		let s:_.args = join(['v:count1', s:_.m, s:_.i, s:_.u], ', ')
-		let s:_.rhs = printf(':<C-U>call wordmotion#object(%s)<CR>', s:_.args)
+		let s:_.rhs = printf('<cmd>call wordmotion#object(%s)<CR>', s:_.args)
 		execute s:_.mode . 'noremap' '<silent>' s:_.map s:_.rhs
 		call s:_.add_existing(s:_.mode, s:_.map, s:_.rhs)
 		if s:_.nomap
```

But is it true that this is not compatible with Vim? :(

**Edit:** It looks like it may be compatible with Vim, actually (I ran into some misinformation that `<cmd>` wouldn't exist in Vim).

**Comment by tuurep** [comment]
By the way, I couldn't figure out the relevance to the `showmode` option, it's just that dot-repeats always show the cmdline call no matter what.
