### ISSUE TITLE
Wordmotion breaks change operator in macros

### ISSUE THREAD

**Issue by nathunsmitty** [chaoren/vim-wordmotion#21]
I recently wrote a macro like this:
```
ct(getFilter^[
```

to fix a piece of code like this:
```js
let f = getConversion(...);
```

I'd expect it to give me:

```js
let f = getFilter(...);
```

When I run this macro from the `g`, I instead get:
```js
const f = call <SNR>71_WordMotion(v:count1, 'o', 'be', [])
tFilter(...)
```

When I run the macro commands manually in normal mode, the desired behavior occurs.

**Comment by chaoren** [comment]
It looks like you found a bug in vim.

What normally happens:

1. `c` enters operator pending mode.
2. `t` enters another operator pending mode.
3. `(` completes the `t` operator, ends one layer of operator pending mode.
4. `t(` combined completes the `c` operator, ends second layer of operator pending mode.
5. The following `ge` is now outside of operator pending mode, and therefore `omap` should not be triggered.

What happens in macros:

Either step 3 or step 4 is not triggered, therefore `ge` still executed under operator pending mode.
You can reproduce this with any `ct`/`cf` and `omap` combination.

**Comment by chaoren** [comment]
https://github.com/vim/vim/issues/3678
