### ISSUE TITLE
Mapping dw and cw causes long delay for dd.

### ISSUE THREAD

**Issue by bitwombat** [chaoren/vim-wordmotion#22]
Hi Chaoren - Thanks for this plugin!

When I `cw` on the word at the end of the line, vim-wordmotion includes the EOL, so I effectively join lines.

I think this is addressed in your README, where you say:

```
If you want to restore Vim's special case behavior with dw and cw, you can do this:

map dw de
map cw ce
```

Problem is, when I do that, `dd` takes a second before acting. Which is weird, because those mappings aren't for `dd`.

It's `map dw de` that's doing it. Without  that, `dd` is instantaneous, like it's supposed to be.

Come to think of it, this doesn't have anything to do with vim-wordmotion, since I can replicate it without the plugin even loading. Perhaps you have some insight anyway?

This is with vim 7.4.1689.

**Comment by chaoren** [comment]
Yes, sorry. Should not have used `map` in the README. `map` expands to `{n,v,o}map` and `omap dw` makes `dd` ambiguous.

**Comment by bitwombat** [comment]
Ah, it really should be

`nnoremap dw de`
and
`nnoremap cw ce`

Otherwise, I'm mapping d in "operator pending mode"

**Comment by chaoren** [comment]
No it has to be `nmap` not `nnoremap`. `nnoremap` bypasses this plugin.
