### ISSUE TITLE
A way to override Vim's W, B, E commands

### ISSUE THREAD

**Issue by proxict** [chaoren/vim-wordmotion#24]
First of all, massive thanks for this plugin. I have been using this plugin for years and I've always taken it for granted, being very surprised when I suddenly had to work in Vim without this plugin.

I've always wished for one more feature of this plugin and that would be the possibility to also override the default Vim's `W`, `B`, `E`, and possibly other commands.
The default behaviour is that Vim stops on the space character on these `W`, `B`, `E` commands. It would be great, in my opinion, if we could also override this behaviour so that Vim would stop on characters like `-.,>` but not on `CamelCase` `snake_case` and so on.

To give an example:
```
|CamelCaseWord->followed_by_snake_case
```
With the current behaviour, when I press `W`, the cursor moves the the end of the line.
What I would like is the cursor stopping on the dash character:
```
CamelCaseWord|->followed_by_snake_case
```

This would allow me to delete the first `CamelCaseWord`, for example, without deleting the rest. Now I have to press `3dw` or 3 times `dw`.

Hopefully it makes sense what I mean.

**Comment by proxict** [comment]
@chaoren Thanks a lot for the feature, really appreciate it! :tada:

**Comment by chaoren** [comment]
Haha, no problem. Sorry for taking a whole year to do it.

**Comment by proxict** [comment]
@chaoren No need to apologize, I totally understand that you're doing this in your free time ;) Had I spent the year learning vimscript, maybe I would have gained the knowledge required to help out ;)
