### ISSUE TITLE
unexpected behavior for cw

### ISSUE THREAD

**Issue by alepinio** [chaoren/vim-wordmotion#27]
Hi,

Let's say we have

```
foo bar
```

and then with cursor on first "o" of "foo" I press `cw`. After doing that, I'm getting

```
fbar
```

Without the plugin I was getting

```
f bar
```

Is that normal behavior?

THX, Alejandro

**Comment by chaoren** [comment]
Please read [the caveats section](https://github.com/chaoren/vim-wordmotion/blob/master/README.md#caveats).
