### ISSUE TITLE
Unexpected behaviour for 'w' in snake_case_words 

### ISSUE THREAD

**Issue by proxict** [chaoren/vim-wordmotion#33]
Hi,

After the implementation of https://github.com/chaoren/vim-wordmotion/issues/24 (which I'm still really grateful for!), I'm facing one issue when I use the 'w' motion in a `snake_case_word`.

I have set the `wordmotion_spaces` variable like this: `let g:wordmotion_spaces = '-.<>()\[\]{}&*=!+"'''`

When I'm at the beginning of the word and I press 'dw', I'd expect it to delete `snake_` so only `case_word` would remain. But instead, it results with `_case_word` (notice the leading underscore).

If I also include an underscore symbol in the `wordmotion_spaces` variable, it works as expected, but it also defeats the purpose of #24. It also works if I don't set the `wordmotion_spaces` variable at all, because then it'll get set to `_` by default.

Is this also one of the plugin's limitations or can this be fixed?

**Comment by chaoren** [comment]
Because the word definitions don't include `_` it'll be treated as its own word. I think I can add a separate spaces variable for uppercase motion (defaults to the existing variable) so you can include `_` in your lowercase one.

**Comment by proxict** [comment]
Ah, I understand.
Adding the new variable would be nice!

**Comment by chaoren** [comment]
I added `g:wordmotion_uppercase_spaces`. I've decided to leave it empty by default because after using it for a while I noticed that uppercase motions skipping underscores threw me off sometimes. I think most users would want different things from these two variables so it's probably best if they don't silenty affect each other.

**Comment by proxict** [comment]
@chaoren , you're my hero, this is exactly what I was looking for, saving my precious time in Vim! Cheers :)
