### ISSUE TITLE
dW will remove word and successive )

### ISSUE THREAD

**Issue by roachsinai** [chaoren/vim-wordmotion#35]
like `[b]ar)`, <kbd>dW</kbd> will remove all `bar)`.

`[]` indicate the cursor position.

Does it by design which is different with Vim origin `dw`.

**Comment by chaoren** [comment]
The plugin by default doesn't map uppercase motions anymore. You're getting default vim behavior. What did you expect `dW` to do? Why should it be the same as lowercase `dw`?

**Comment by roachsinai** [comment]
ah, my fault! So sorry to bother!
