### ISSUE TITLE
Work with Surround plugin

### ISSUE THREAD

**Issue by albert-ying** [chaoren/vim-wordmotion#37]
This is a very useful plugin, especially when I have long_variable_name and need to change part of it. However, when working with surround, it is not very handy.

E.g. 
[l]ong_variable_name1, long_variable_name2, ... 
do ysw" and I got:
"long_"variable_name1, long_variable_name2, ...; 
do ysW" and I got:
"long_variable_name1," long_variable_name2, ...

But most of the time, people want "long_variable_name1",  and I cannot achieve this.

I'm wondering is there any workaround for this?

**Comment by chaoren** [comment]
It's 3 words now, does `ys3w"` work for you?

I prefersonally prefer to select first, then surround (`v3eS"`) so I can see exact text I'm acting on.

**Comment by chaoren** [comment]
You can also create a map to the default `w` motion and use that instead for these cases.

E.g., `onoremap ,w w` in your `.vimrc` and then `ys,w"`.

**Comment by proxict** [comment]
Or you can configure the uppercase movement separately from the lowercase one:
let g:wordmotion_spaces = '_'
let g:wordmotion_uppercase_spaces = '-.,<>()\[\]{}&*=!+;:'

That way, if you do `ysE"`, you should get what you expect.
