### ISSUE TITLE
Unsure how to customize

### ISSUE THREAD

**Issue by kshenoy** [chaoren/vim-wordmotion#4]
Hi, I'm sorry but I didn't quite follow how to setup my own keys.

Let's say I want to preserve the default behavior of 'w', 'W', 'b', 'B', 'e', 'E', 'ge' and 'gE'. And I want to set up new motions `<M-w>`, `<M-e>`, `<M-b>` to perform camel-case etc. traversal. What do I need to do?

**Comment by chaoren** [comment]
This plugin doesn't touch `W`, `B`, `E`, or `gE` by default, so you don't have to worry about those.
```
let g:wordmotion_mappings = {
	'w' : '<M-w>',
	'b' : '<M-b>',
	'e' : '<M-e>',
	'ge' : 'g<M-e>',
	'aw' : 'a<M-w>',
	'iw' : 'i<M-w>'
}
```
should do what you want.

**Comment by kshenoy** [comment]
Instead of using consider using `<Plug>`s. It's more portable and also allows for some fancy things like allowing lazy loading by plugin managers.

Thanks for a great plugin :)

**Comment by chaoren** [comment]
> Instead of using consider using <Plug>s.

Instead of using what?

**Comment by kshenoy** [comment]
Whoops, I meant "instead of using a dictionary to specify maps".  The advantage is if someone uses a plugin manager which allows lazy loading, they can do something like [this](https://github.com/kshenoy/dotvim/blob/7d0cb4694bdef06c0346f6fd5f3c3f4fc9292b46/bundle.vim#L23).

This will cause the plugin to be loaded only when the maps are actually used.

**Comment by chaoren** [comment]
> It's more portable

It's vimscript, how is anything more portable than another? Unless you mean some old vim version doesn't support one, but does support the other. I don't think that's the case, and honestly don't care even if it is.

> The advantage is if someone uses a plugin manager which allows lazy loading

You can do this:
```
let g:wordmotion_mappings = {
    'w' : '<Plug>WordmotionW',
    'b' : '<Plug>WordmotionB',
    ...
}
map <M-w> <Plug>WordmotionW
map <M-b> <Plug>WordmotionB
...
```
I know what the other plugin does. I personally think that's extremely ugly, and option variables with the form `g:<plugin name>_<option name>` are much cleaner and easier to keep track of. This workaround I just gave you is also extremely ugly, but you're free to do whatever you want.

Another thing is that lazy loading for tiny plugins like these are really not important, but if you're that serious about saving 10 nanoseconds of load time, then go for it. This is also why I didn't use autoloading at all. It's so pointless for a plugin of this size.

**Comment by kshenoy** [comment]
> This is also why I didn't use autoloading at all. It's so pointless for a plugin of this size.

That is a good point; I didn't consider that in my haste to lazy load every plugin that I could.

Thanks for your help.
