### ISSUE TITLE
Using 'cw' on a last word in the line if the next line is indented joins the lines

### ISSUE THREAD

**Issue by MasterMedo** [chaoren/vim-wordmotion#41]
![wordmotion](https://user-images.githubusercontent.com/16375100/100217859-3d589900-2f14-11eb-885e-d417afd78658.gif)

init.vim:
```vim
call plug#begin('~/.vim/plugged')
Plug 'chaoren/vim-wordmotion'
call plug#end()

" when using 'cw' on the last word
  " and the next line is indented it joins them
```

version: NVIM v0.4.4

**EDIT:** even when doing:
```vim
nmap dw de
nmap cw ce
```
doing cw/dw on the very last character still joins the lines

**Comment by chaoren** [comment]
This is the same issue as #36. I've decided to implement vim's cw/dw behavior. Stay tuned.
