### ISSUE TITLE
Unexpected behaviour for dw on files with a shebang and no extension

### ISSUE THREAD

**Issue by Ninjaclasher** [chaoren/vim-wordmotion#50]
On files with a shebang and no extension, `dw` seems to only delete a single character, rather than until the beginning of the next word.

### Reproduction
Create four files (only the first one demonstrates the unintended behaviour, but the other three show (what I believe) the intended behaviour should be).
```sh
$ cat test1
#!/usr/bin/env python3
print('test')
```
```sh
$ cat test2
print('test')
```
```sh
$ cat test3.py
print('test')
```
```sh
$ cat test4.py
#!/usr/bin/env python3
print('test')
```

Reopen each file individually (opening all at the same time does not seem to invoke the unintended behaviour), and with cursor over the `p` in `print`, press `dw`. For `test1`, a single character is deleted, resulting in `rint('test')`. For all of `test2`, `test3.py`, and `test4.py`, the result is `('test')`.

### Intended Behaviour
From my understanding, in all four cases, the result should be `('test')`. Please correct me if I'm misunderstanding something.

**Comment by chaoren** [comment]
I think you have another plugin using the `w` mapping. Can you run `:verbose map w` with the problematic file open?

**Comment by Ninjaclasher** [comment]
The output I got was
```
o  w             <Plug>WordMotion_w
        Last set from ~/.config/nvim/plugged/vim-wordmotion/plugin/wordmotion.vim line 60
x  w             <Plug>WordMotion_w
        Last set from ~/.config/nvim/plugged/vim-wordmotion/plugin/wordmotion.vim line 60
n  w             <Plug>WordMotion_w
        Last set from ~/.config/nvim/plugged/vim-wordmotion/plugin/wordmotion.vim line 60
```

**Comment by chaoren** [comment]
This is with `test1` open, right? I can't actually reproduce your issue.

1. Try with vim instead of neovim.
2. Try launching with no other plugins: `vim -Nu <(echo 'set rtp=$HOME/.config/nvim/plugged/vim-wordmotion') test1`
3. How do other motions behave? E.g., `db`, `de`.
4. Does the `w` motion (without `d`) still work?

**Comment by chaoren** [comment]
Also please share any plugins options you may have set.

**Comment by Ninjaclasher** [comment]
Upon further debugging, it seems that this unexpected behaviour may be a problem with [lh-brackets](https://github.com/LucHermitte/lh-brackets), since disabling either vim-wordmotion or lh-brackets results in the correct behaviour. (Woops, missed your comment by a few seconds...)

To respond to your comments,
1. This issue still persists with vim (with my current set of plugins).
2. This issue doesn't persist with no other plugins (see comment above).
3. `de` works as intended. `db` has a similar issue with `dw`.
4. `w` works as intended.

My plugin set is
```
Plug 'suan/vim-instant-markdown', {'for': 'markdown'}
Plug 'LucHermitte/lh-brackets'
Plug 'LucHermitte/lh-vim-lib'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mbbill/undotree'
Plug 'tpope/vim-fugitive'
Plug 'lervag/vimtex', {'for': 'tex', 'commit': '7c886a0731f1aa283899575615b75192ec3632b7'}
Plug 'chaoren/vim-wordmotion'
```
with options
```
let g:usemarks=0                     
let g:cb_jump_over_newlines=0             
                                        
let g:instant_markdown_slow=1                
let g:instant_markdown_autostart=0      
let g:instant_markdown_mathjax=1             

let g:airline_theme='onedark'            
                                         
let g:tex_flavor='latex'                 
let b:tex_stylish=1                      
let g:vimtex_quickfix_open_on_warning=0
let g:vimtex_quickfix_mode=0      
let g:vimtex_view_general_viewer='zathura'
let g:vimtex_syntax_autoload_packages=['amsmath','tikz']
```

**Comment by chaoren** [comment]
You should try filing a bug with `lh-brackets`. This plugin doesn't deal with file types, and that one does. It's doing something different in the case of extension-less python files at least. Is it only python files? Or does any other shebang cause the issue?

**Comment by Ninjaclasher** [comment]
Thanks for looking into it. As a followup to your question, it happens with any other files with a shebang (tried with `#!/bin/sh`).
