### ISSUE TITLE
Leading underscore as non-whitespace?

### ISSUE THREAD

**Issue by byron-hawkins** [chaoren/vim-wordmotion#55]
For `private` fields in a C++ class, I'm using the convention of a leading underscore, like `_length` or `_id`. With the default wordmotion settings, `w` moves to the first letter and will never stop on the underscore. In any other case, with the underscore in the middle or at the end of a word, that works fine. But it becomes very awkward for example to copy these private field identifiers because I can't `w` to the start of the word. Is there a way to configure wordmotion so that a leading underscore is a totally different character than an internal underscore? Or if not, can the position of the underscore be taken into account, so that the leading underscore becomes equivalent to a letter? Thanks for any suggestions.

**Comment by chaoren** [comment]
> With the default wordmotion settings, `w` moves to the first letter and will never stop on the underscore.

The default behavior is:
````
    ____foo____bar____
w-->w-->w->w-->w->w->w
````

It does exactly what you expect.
Did you change any settings?

**Comment by chaoren** [comment]
https://github.com/chaoren/vim-wordmotion#gwordmotion_spaces

> NOTE: make sure the regex matches a single character. You can use lookaheads and lookbehinds for context-sensitive space characters.
> NOTE: the default patterns match 1) hyphens (`-`) between between alphabetic characters and 2) underscores (`_`) between alphanumeric characters.

**Comment by chaoren** [comment]
If you set `g:wordmotion_spaces` at all then it's going to do the dumb matching. The default pattern is quite complex and does only match underscores/hyphens between characters: `['\%([[:lower:][:upper:][:digit:]]_*\)\@<=_\%(_*[[:lower:][:upper:][:digit:]]\)\@=', '\%([[:lower:][:upper:]]-*\)\
@<=-\%(-*[[:lower:][:upper:]]\)\@=']`.

**Comment by byron-hawkins** [comment]
I had an old version, so after updating it works just like you explained. Thanks! Also added a watch on this repository so I won't miss any future updates.
