### ISSUE TITLE
cw with count not work correctly

### ISSUE THREAD

**Issue by yioneko** [chaoren/vim-wordmotion#57]
It seems that the count work as expected only when the cursor is placed at the end of the word:
![2](https://user-images.githubusercontent.com/65551246/132970002-a4d67ceb-b848-41a9-8038-ae93b43a6c43.gif)

I suspect that here 
https://github.com/chaoren/vim-wordmotion/blob/0edeebdfa95c0a1fc5fbb83b8faf6b0b2cc3bf7e/autoload/wordmotion.vim#L118-L124
shouble be
```vimL
 if l:count == 1 && l:cw 
	let l:flags .= 'c' 
 endif 
 while l:count > 0 
 	call search('\m'.l:pattern, l:flags.'W') 
 	let l:count -= 1 
 endwhile 
```
And I've tested it and it works as expected after the modification, but I'm not sure whether it will break other stuff.

**Comment by chaoren** [comment]
Thanks for the report. Looks like the existing tests only covered `cw` with count for single character words. Whoops.
