### ISSUE TITLE
provide a toggle command

### ISSUE THREAD

**Issue by ninrod** [chaoren/vim-wordmotion#6]
First of all, awesome plugin, thank you.

Consider providing a `:ToggleWordMotion` command.

Rationale: prefixing wordmotion bindings commands with `<leader>` is not ideal. I more often need wordmotions defaults than not.

Temporarily disabling wordmotion would be faster if, for example, want to refactor `var a=[a][b][a_really_huge_variable_using_the_normal_w_vim_motion];`.

I'm leaving wordmotion with the default bindings and using `:norm! ciw` when I want to operate as described above. But that feels clunky.

**Comment by chaoren** [comment]
Do you mean you want to use `ciw` on `[a_really_huge_variable_using_the_normal_w_vim_motion]`?
Why not `ci[`?

I'm not sure this is necessary.
1. If you use this plugin's word motions more often, then you use it with the default mappings and `nnoremap` something else to the regular word motions.
2. On the other hand, if you use regular word motions more often, then you can use this plugin's word motions with a prefix or something.

You could also consider applying a custom mapping only on the `iw` and `aw` commands, so the regular vim word objects are available.

`i(`, `i[`, `i{`, `i"`, `iW` (`WORD` not `word`), etc, seems to cover most cases where you want larger text objects than provided by this plugin.

**Comment by chaoren** [comment]
I'm leaving this open.I will consider it if you can provide reasonable examples where the suggestions I gave above don't work.

**Comment by ninrod** [comment]
You are right. The example was poor because you could circumvent the problem using `ci[` or similar bindings. But having a convenient surrounding arround the big word will not always bethe case. 

let us consider this snippet for a moment:

```bash
if [[ -n ${GIT_USER_NAME+x} ]]; then
  git config --global user.name $GIT_USER_NAME
  export GIT_USER_NAME
fi
```
let us suppose that user wants to refactor `GIT_USER_NAME`. With `vim-wordmotion` defaults there is no easy way to do that. Of course that `:norm! ciw` would function here. But dropping a whole ex-command to achieve the solution does feel clunky. You `ct+` if you were on the beggining of the word. But what if the cursor is above the `N` of git user name? `bbct+`? clunky. 

```sh
  local plug_dir=$(realpath -m $really_poorly_named_user_directory)
  if [[! -d $sytem_wide_plug_horrendous_named_dir]]; then
    echo -e "installing ${Yellow}vim${Rst} plugins..."
    vim +PlugInstall +qall
  fi
```

Now imagine you want to rename those awful named variables. I think now I managed to get the picture across. That's the nagging issue.

**Comment by chaoren** [comment]
`ciW` (`WORD` not `word`) works, retyping the `$` is not *that* bad.

**Comment by chaoren** [comment]
And you can always do something like:
```
noremap io iw
noremap ao aw
```
and do `cio`, where `o` means original.

**Comment by chaoren** [comment]
I think it's more annoying to have to:
1. Toggle original motions on.
2. Make original motion.
3. Toggle original motions off.
rather than just try using another mapping, or if it *must* be the original `w` motion, set a different mapping for the original.

**Comment by chaoren** [comment]
This works too:
```
let g:wordmotion_mappings = { 'iw' : 'ii', 'aw' : '' }
```
and continue to use `ciw` for regular words, but only use `cii` for "inner" words.

**Comment by ninrod** [comment]
hum, yeah. The `cio` bind solves the problem nicely. Thanks for pointing out that free bind, by the way. Finding free bindings like that in vim is an art form.
