### ISSUE TITLE
Broken lsp rename

### ISSUE THREAD

**Issue by EricDriussi** [chaoren/vim-wordmotion#66]
Hi there!

I just noticed that the plugin doesn't interact quite well with nvim's lsp `lua vim.lsp.buf.rename()`.

Say for example I'm renaming `nice_variable` to `cool_variable` with the cursor over the word `varible` by launching the above mentioned command.
The prompt will ask what to replace `variable` with, instead of `nice_variable''.

Is this the expected behavior?

**Comment by chaoren** [comment]
Sorry, I don't use nvim. Does it happen without my plugin? I haven't added anything special to handle nvim or their LSP feature. You could probably file a bug against them instead.

**Comment by chaoren** [comment]
https://neovim.io/doc/user/lsp.html

```
rename({new_name}, {options})                           *vim.lsp.buf.rename()*
                Renames all references to the symbol under the cursor.
```

Seems like it works based on cursor location and not motion, so I have no clue how my plugin could affect their function.

**Comment by EricDriussi** [comment]
Well, turns out I'm retarded -.-U
I had `iskeyword-=_` and `iskeyword-=-` set in `/etc/xdg/nvim/sysinit.vim`, **this** was causing the issue, not your plugin :man_facepalming: 
Just by chance, i set those right before finding your plugin and forgot, so I just assumed it was the plugin.

Anyway, sorry about that!
