### ISSUE TITLE
use vim default word definition for `WORD`

### ISSUE THREAD

**Issue by psteinroe** [chaoren/vim-wordmotion#71]
hey, thanks for the plugin. was looking for something like it and works like a charm. After using it for a while, I would prefer to use the default word definition for `WORD`. Is that config possible? I could not find it in the docs.

thanks!

**Comment by Arnie97** [comment]
Did you mean mapping the `WORD` keys as Vim native `word` motions:

```vim
noremap W w
noremap B b

...

xnoremap aW aw
onoremap aW aw
xnoremap iW iw
onoremap iW iw
```

Or, keeping the `WORD` keys as Vim native `WORD` motions:

```vim
let g:wordmotion_mappings = {'W': '', 'B': '', 'E': '', 'gE': '', 'aW': '', 'iW': ''}
```

**Comment by psteinroe** [comment]
thanks for the quick reply! I am looking to map `WORD` to the vim native `word` motions. I tried converting the remaps to lua with 

```lua
-- overwrite WORD definition to word
vim.keymap.set("n", "W", "w", {remap= true})
vim.keymap.set("n", "B", "b", {remap= true})
vim.keymap.set("x", "aW", "aw", {remap= true})
vim.keymap.set("o", "aW", "aw", {remap= true})
vim.keymap.set("x", "iW", "iw", {remap= true})
vim.keymap.set("o", "iW", "iw", {remap= true})
```

but it doesn't work. Any help would be much appreciated.

**Comment by chaoren** [comment]
> ```lua
> -- overwrite WORD definition to word
> vim.keymap.set("n", "W", "w", {remap= true})
> vim.keymap.set("n", "B", "b", {remap= true})
> vim.keymap.set("x", "aW", "aw", {remap= true})
> vim.keymap.set("o", "aW", "aw", {remap= true})
> vim.keymap.set("x", "iW", "iw", {remap= true})
> vim.keymap.set("o", "iW", "iw", {remap= true})
> ```

I'm not familiar with that lua API, but you probably want `{remap = false}` instead. Otherwise, your `W` would map to `w` and follow its map to the plugin mappings. `noremap` prevents this kind of mapping recursion.

**Comment by psteinroe** [comment]
> but you probably want `{remap = false}` instead

that fixed it, thanks!!
