### ISSUE TITLE
wordmotion_prefix not working when using Lazy plugin manager

### ISSUE THREAD

**Issue by lubaroli** [chaoren/vim-wordmotion#72]
I've recently migrated to Lazy from Packer and it seems this has broken support to wordmotion_prefix.

You can reproduce this with the following minimal configuration:
```
-- bootstrap lazy
--
local lazy_path = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazy_path) then
   vim.fn.system({
      "git",
      "clone",
      "--filter=blob:none",
      "https://github.com/folke/lazy.nvim.git",
      "--branch=stable", -- latest stable release
      lazy_path,
   })
end
vim.opt.rtp:prepend(lazy_path)

-- plugins
--
require("lazy").setup({
   { "chaoren/vim-wordmotion" }, -- more precise word motion
})

vim.g.wordmotion_prefix = ","
```

Running `:map w` outputs:
```
o  w             <Plug>WordMotion_w
x  w             <Plug>WordMotion_w
n  w             <Plug>WordMotion_w
```

**Comment by chaoren** [comment]
I don't use neovim or any of those package managers you mentioned. I'm assuming they're package managers. I'm also not interested in installing them just to reproduce your issue.

Please describe exactly what is broken. Does `w` just not do anything? Does it move but incorrectly?

`:map w` shows that it's correctly mapped to the internal mappings. What does `:map <Plug>WordMotion_w` show? If that's mapped to a function call, then you're probably just having trouble loading functions from the `autoload` directory. Please look into the documentation of the package managers to see how you're supposed to configure them to handle `autoload` functions.

**Comment by lubaroli** [comment]
Thanks for your reply, I've sorted it out with the help from folks from Lazy. The global had to be set before loading the plugin.
