### ISSUE TITLE
Make w recognize - and CamelCase and W do what w used to do?

### ISSUE THREAD

**Issue by bkerin** [chaoren/vim-wordmotion#76]
As the subject says. It looks like this should be possible with a big ilst in g:wordmotion_uppercase_spaces but it might be nice to have some easy way to do this (maybe just a var lying around that could be advertised in the docs).  People  who don't like lots of white space just never use W so it's likely a common want.

**Comment by chaoren** [comment]
> It looks like this should be possible with a big ilst in g:wordmotion_uppercase_spaces

`g:wordmotion_uppercase_spaces` is a list of regular expressions, so you could just have a regex that matches any non-alphanumeric character.

Try
```vim
let g:wordmotion_uppercase_spaces = ['[^[:alnum:]]']
```

> People who don't like lots of white space just never use W so it's likely a common want.

You're the first person to ask for this, so I don't think it's that common.

**Comment by bkerin** [comment]
Turns out what I really want is for W to mean what w used to mean, which I imagine comes under the remap voodoo department

**Comment by chaoren** [comment]
> what w used to mean

Do you mean the default vim behavior without this plugin? Can't you just do `noremap W w`?

**Comment by bkerin** [comment]
yes I've realized that now.  sorry I go years a build up a zillion little things that annoy me and then go on a binge fixing them but I forget how vi innards works in between.  WordMotion is fixing a very longstanding annoyance that has only gotten worse with current camelcase fashion, thanks for doing it
