### ISSUE TITLE
yank or delete support

### ISSUE THREAD

**Issue by mantriyogesh** [chaoren/vim-wordmotion#81]
It was very important feature, I think vim missed by default.
Thank you for implementation of this idea.

is it possible to **disable**/customize word completion for yank or delete?
Now I have habit (like bunch of others would have too), to use dw or yw. but with this plugin, by default it is treating similar to browsing of words.

for example, 
Out of habit, i want to copy 
```
this_is_big_string
```
if the cursor is at start of word and i do yw, it would copy 'this' instead of full `this_is_big_string`

**Comment by chaoren** [comment]
You can either `map` back to the original `dw`/`yw` like this:

```vim
nnoremap dw dw
nnoremap yw yw
```

or remove the `omap` after the plugin loads:
```vim
ounmap w
```

**Comment by mantriyogesh** [comment]
Perfect @chaoren !

```
nnoremap dw dw
nnoremap yw yw
```
Works like charm!

Thanks for the quick reply..
