### ISSUE TITLE
cw takes whitespace between words

### ISSUE THREAD

**Issue by oblitum** [chaoren/vim-wordmotion#9]
Is it intentional to consume the whitespace between words? I'm getting myself frequently making mistakes because of this change, for example in `|foo bar` (cursor is `|`), I see that for `dw` it's indeed useful to delete whitespace, maybe, but for `cw` it doesn't make much sense, even more because it's inconsistent with `ciw` that whose purpose is to change word from inside the word, but it differs from behavior given that it doesn't consume whitespace, as in usual Vim.

**Comment by oblitum** [comment]
Hmm, OK, now I got that the caveat section in the README is about this... I just don't understand why this was chosen...

**Comment by chaoren** [comment]
You want `de` (or `ce`) instead of `dw` (or `cw`). If you consider the actual motion of `w` (which is totally different from `iw`), Vim is the inconsistent one here. If you prefer the original behavior just do this:
```
map dw de
map cw ce
```
Or just train yourself to use the correct `e` version.

**Comment by oblitum** [comment]
Ah, OK thanks :) I'll try to train that.

**Comment by oblitum** [comment]
I suggest a mention of `de` and `ce` in README, as `dw` and `cw` is so popular... newbies may miss it in general.

**Comment by chaoren** [comment]
It is there:

"This plugin faithfully follows the motion of w, while Vim replaces these two special cases with the behavior of `de` and `ce`, respectively."

**Comment by oblitum** [comment]
Ah, I didn't connect the dots because there was no reference to `dw`/`cw`, which is what I got used to.

**Comment by chaoren** [comment]
`dw` and `cw` is in the big diagram. Is it hard to read? I'll add `dw` and `cw` to the text then.

**Comment by oblitum** [comment]
Well, there're references in the diagram above indeed... but I didn't connect `ce` was brother of `cw` because of the distance in text. Enough excuses huh? :)

**Comment by tmandry** [comment]
I also didn't realize from the README that I could just map dw and cw. Glad I found this issue. The mention of "special cases" made me think that it wasn't that simple.

**Comment by chaoren** [comment]
https://github.com/vim/vim/blob/b45125b374cc3a1cef176b704f518c72c518f24c/runtime/doc/motion.txt#L413

> Special case: "cw" and "cW" are treated like "ce" and "cE" if the cursor is
on a non-blank.  This is because "cw" is interpreted as change-word, and a
word does not include the following white space.  {Vi: "cw" when on a blank
followed by other blanks changes only the first blank; this is probably a
bug, because "dw" deletes all the blanks}

It really is just a special case.
